name: Main build
on: 
  push:
    branches:
      - 'main'

jobs:
  builds:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true 

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore 

      - name: Build mod file
        run: |
          Compress-Archive ./Zeepkist.RandomTrack/bin/Release/net472/Zeepkist.RandomTrack.dll,./Zeepkist.RandomTrack/bin/Release/net472/*.csv mod.zip

      - name:  Upload to mod.io
        uses: nickelc/upload-to-modio@v2.1.0
        with:
          token: ${{ secrets.MODIO_TOKEN }}
          game: ${{ vars.GAME_ID }}
          mod: ${{ vars.MOD_ID }}
          path: mod.zip
          version: ${{ env.GitVersion_MajorMinorPatch }}
          changelog-path: changelog.txt
